apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WORDPRESS_DB_HOST: 'mysql-service'
  WORDPRESS_DB_USER: 'wpuser'
  WORDPRESS_DB_PASSWORD: 'wppassword'
  WORDPRESS_DB_NAME: 'wordpress'
---

apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wp-pod
spec:
  containers:
    - name: wp-container
      image: wordpress
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: wordpress-config

---

apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wp-service
spec:
  ports:
    - name: wp-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wp-pod

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - http:
            paths:
            - path: /(.*)
              pathType: Prefix
              backend:
                service:
                  name: wp-service
                  port:
                    number: 80
