apiVersion: v1
kind: Pod
metadata:
  name: my-app-cm
  namespace: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: nginx
      env:
        - name: TITLE
          value: Toto
        - name: MyName
          value: Here is my name
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: my-app-config
      volumeMounts:
        - mountPath: /opt/my-app
          name: my-file
  volumes:
    - name: my-file
      configMap:
        name: my-app-config
        items:
          - key: MY_FILE
            path: my_file.txt
