kubectl apply -f ./grafana/templates/secret.yaml
kubectl apply -f ./grafana/templates/service.yaml
kubectl apply -f ./grafana/templates/clusterrolebinding.yaml
kubectl apply -f ./grafana/templates/configmap.yaml
kubectl apply -f ./grafana/templates/serviceaccount.yaml
kubectl apply -f ./grafana/templates/pvc.yaml
kubectl apply -f ./grafana/templates/rolebinding.yaml
kubectl apply -f ./grafana/templates/deployment.yaml
kubectl apply -f ./grafana/templates/clusterrole.yaml
kubectl apply -f ./grafana/templates/role.yaml
