kind: Deployment
apiVersion: apps/v1
metadata:
  name: custom-metrics
  labels:
    app.kubernetes.io/name: custom-metrics
    app: custom-metrics
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-metrics
      app: custom-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-metrics
        app: custom-metrics
    spec:
      containers:
        - name: custom-metrics
          image: kaylleur/myapp:4.0.3
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics
  labels:
    app.kubernetes.io/name: custom-metrics
    app: custom-metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
spec:
  type: "ClusterIP"
  ports:
    - name: "http"
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: custom-metrics
    app: custom-metrics
