kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
data:
  config_yml: |
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 1m
        static_configs:
          - targets: ['localhost:9090']
    
      - job_name: 'node'
        scrape_interval: 15s
        static_configs:
          - targets: ['node-exporter:9100']



---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometheus-storage
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: config_yml
                path: prometheus.yml
        - name: prometheus-storage
          emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
